#
# This Makefile just invokes any rule in the Makefile in the parent directory
# as a convenience.
#
# No need to add anything here.
#

all:

# Any target rule just gets passed up to parent Makefile
%:
	@$(MAKE) -C .. $@
